### ISSUE TITLE
Error to parse URL starts with protocol svn and git in attribute repository_url

### ISSUE THREAD

**Issue by soul2zimate** [jboss-set/jboss-streams#20]
```
Caused by: org.jboss.set.aphrodite.spi.AphroditeException: Unable to initiatilise Aphrodite as an error was thrown when initiating org.jboss.set.aphrodite.stream.services.json.JsonStreamService: org.jboss.set.aphrodite.spi.NotFoundException: javax.json.JsonException: Unable to parse url: unknown protocol: svn
	at org.jboss.set.aphrodite.Aphrodite.initialiseStreams(Aphrodite.java:197)
	at org.jboss.set.aphrodite.Aphrodite.init(Aphrodite.java:177)
	at org.jboss.set.aphrodite.Aphrodite.<init>(Aphrodite.java:139)
	at org.jboss.set.aphrodite.Aphrodite.instance(Aphrodite.java:89)
```
JsonStreamService throws exception when it parses attribute repository_url as it can not properly handle protocols like svn and git.
I have committed https://github.com/jboss-set/jboss-streams/commit/6f70a17e31e1f0ab009d09a988d7f087e31fd0a0 to remove the problematic values, keep this open until Aphrodite can properly resolve these values and we can add them back.

**Comment by baranowb** [comment]
Fixed via:
https://github.com/jboss-set/jboss-streams/pull/21
https://github.com/jboss-set/jboss-streams/pull/23
